version: '3.4'

services:
  clinicparser:
    image: clinicparser
    build:
      context: .
      dockerfile: ./Dockerfile
      # args:
      #   http_proxy: http://192.168.36.220:8080
    ports:
      - 8000:8000
