version: '3.4'

services:
  clinicparser:
    image: clinicparser
    volumes:
      - ./readablepdf/:/readablepdf
    build:
      context: .
      #dockerfile: ./Dockerfile
      dockerfile: ./DockerfileInternet
      # args:
      #   http_proxy: http://192.168.36.220:8080
    ports:
      - 8000:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
